app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('/web');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
//    \Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {
//        var_dump($query->sql);
//        var_dump($query->bindings);
//        var_dump($query->time);
//    });
    Route::controllers([
        'app'       => 'AppController',
        'web'       => 'WebController',
        'admin'     => 'AdminController',
        'email'     => 'EmailController',
        'student'   => 'StudentController',
        'wbt'       => 'CBTController',
        'auth'      => 'AuthController'
    ]);
});

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    //
    public function option(){
        return $this->hasMany('\App\Option');
    }
    
    public function exam(){
        return $this->belongsTo('\App\Exam');
    }

    public function questionAdditionalInformation(){
        return $this->belongsTo('\App\QuestionAdditionalInformation');
    }

    public function getQuestionAdditionalInformationIdAttribute($value){
        if($value)
            return $value;
        FALSE;
    }
}

resources/views/admin/addexam.blade.php
@extends('admin_layout')

@section('pagetitle')
EXAMINATION RESOURCES MANAGER - <small>Add Examination</small>
@stop
@section('maincontent')
<div class="tab-v1">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#home" data-toggle="tab">Examination Options</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="home">
            <div class="row">
                <div class="col-md-12">
                        {!! Form::open(array('url' => url('wbt/add-examination'),'class'=>'sky-form', 'id'=>'sky-form')) !!}
                        <fieldset>
                            <div class="row">
                                <section class="col col-4">
                                    <label class="select">
                                        <span>EXAM PROVIDER</span>
                                        <select name="provider">
                                            <option value="0" selected disabled>Exam Provider</option>
                                            @foreach($providers as $provider)
                                            <option value="{{$provider->id}}">{{$provider->name}}</option>
                                            @endforeach
                                        </select>
                                    </label>
                                </section>
                                <section class="col col-4">
                                    <label class="select">
                                        <span>EXAM SUBJECT</span>
                                        <select name="subject_id" class="select">
                                            <option value="0" selected disabled>Exam Subject</option>
                                            @foreach($subjects as $subject)
                                            <option value="{{$subject->id}}">{{$subject->name}}</option>
                                            @endforeach
                                        </select>
                                    </label>
                                </section>
                                <section class="col col-4">
                                    <label class="input">
                                        <span>TOTAL TIME ALLOWED</span>
                                        <div class="row">
                                            <div class="col-md-4">
                                                <input type="text" name="hr" placeholder="Hr.">
                                            </div>
                                            <div class="col-md-4">
                                                <input type="text" name="min" placeholder="Min.">
                                            </div>
                                            <div class="col-md-4">
                                                <input type="text" name="sec" placeholder="Sec.">
                                            </div>
                                        </div>
                                    </label>
                                </section>
                            </div>
                            <div class="row">
                                <section class="col col-4">
                                    <label class="select">
                                        <span>EXAM YEAR</span>
                                        <select name="session_id" class="select">
                                            <option value="0" selected disabled>Exam Year</option>
                                            @foreach($sessions as $session)
                                            <option value="{{$session->id}}">{{$session->name}}</option>
                                            @endforeach
                                        </select>
                                    </label>
                                </section>
                                <section class="col col-4">
                                    <label class="select">
                                        <span>EXAM MONTH</span>
                                        <select name="month_id">
                                            <option value="0" selected disabled>Exam Month</option>
                                            @foreach($months as $month)
                                            <option value="{{$month->id}}">{{$month->name}}</option>
                                            @endforeach
                                        </select>
                                    </label>
                                 </section>
                                <section class="col col-4">
                                    <label class="select">
                                        <span>INSTRUCTION</span>
                                        <select name="instruction" class="select">
                                            <option value="0" selected disabled>Exam Instruction</option>
                                            @foreach($instructions as $instruction)
                                            <option value="{{$instruction->id}}">{{$instruction->title}}</option>
                                            @endforeach
                                        </select>
                                    </label>
                                </section>
                            </div>
                        </fieldset>
                        <footer>
                            <div class="pull-right">
                                <button type="submit" class="btn-u">Save and Add Questions</button>
                            </div>
                        </footer>
                    {!! Form::close() !!}
                </div>

            </div>
        </div>
    </div>
</div>
@stop
@section('pagecss')
<link rel="stylesheet" href="{{ asset('public/assets/plugins/sky-forms-pro/skyforms/css/sky-forms.css')}}">
<link rel="stylesheet" href="{{ asset('public/assets/plugins/sky-forms-pro/skyforms/custom/custom-sky-forms.css')}}">
@stop
@section('pageplugins')
<script type="text/javascript" src="{{ asset('public/assets/plugins/sky-forms-pro/skyforms/js/jquery.validate.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('public/assets/plugins/sky-forms-pro/skyforms/js/jquery.maskedinput.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('public/assets/plugins/sky-forms-pro/skyforms/js/jquery-ui.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('public/assets/plugins/sky-forms-pro/skyforms/js/jquery.form.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('public/assets/js/forms/checkout.js')}}"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
                        OrderForm.initOrderForm();
			ReviewForm.initReviewForm();
			CheckoutForm.initCheckoutForm();
                    });
//    CKEDITOR.replace('texteditor');
</script>
@stop

resources/views/admin/addexaminationquestionedit.blade.php
<div class="row">
    <div class="col-md-12">
        {!! Form::open(array('url' => url('wbt/update-examination-question'),'class'=>'sky-form', 'id'=>'sky-form')) !!}
        <input type="hidden" name="questionid" value="{{\Crypt::encrypt($question->id)}}">
            <fieldset>
                <div class="row">
                    <div class="col-md-8">
                        <section>
                            <label class="textarea">
                                <span>QUESTION TEXT</span>
                                <textarea rows="2" name="question_name" placeholder="Question Text" id="question" required>{{$question->name}}</textarea>
                            </label>
                        </section>
                    </div>
                    <div class="col-md-4">
                        <section>
                            <a rows="4" class="btn-u" data-toggle="modal" data-target="#add_info" style="padding:6px 70px; margin-top:20px;">New Additional Information</a>
                        </section>
                        <section>
                            <label class="select">
                                <span>ADDITIONAL INFORMATION</span>
                                <select id="additional_info" name="add_info" data-placeholder="Choose a Additional Information..." class="form-control chosen-select" tabindex="2"></select>
                            </label>
                        </section>
                        <section>
                            <span class="icon-info" id="select_preview_title" style="display:none;"></span>
                            <img id="img_select_preview" src="" height="250" width="310" alt="Image preview..." >
                            <div id="desc_select_preview" style="display:none;"></div>
                        </section>
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <div class="row">
                    <div class="col-md-8">
                        <section>
                            <label class="input">
                                <div class="row">
                                    {{--*/$count=1;/*--}}
                                    <div class="col-md-1">
                                        <label class="radio">
                                            <input type="radio" name="answer" value="{{$count}}" required {{($options->count() > 0 && $options[0]->status == 1)? 'checked':''}}>
                                            <i class="rounded-x"></i>
                                        </label>
                                    </div>
                                    <div class="col-md-11">
                                        <input type="text" name="option1" placeholder="Option A" value="{{($options->count() > 0)? $options[0]->name:''}}" required>
                                    </div>
                                </div>
                            </label>
                            <label class="input">
                                <div class="row">
                                    {{--*/$count++;/*--}}
                                    <div class="col-md-1">
                                        <label class="radio">
                                            <input type="radio" name="answer" value="{{$count}}" required {{($options->count() > 1 && $options[1]->status == 1)? 'checked':''}}>
                                            <i class="rounded-x"></i>
                                        </label>                                    </div>
                                    <div class="col-md-11">
                                        <input type="text" name="option2" placeholder="Option B" value="{{($options->count() > 1)? $options[1]->name:''}}" required>
                                    </div>
                                </div>
                            </label>
                            <label class="input">
                                <div class="row">
                                    {{--*/$count++;/*--}}
                                    <div class="col-md-1">
                                        <label class="radio">
                                            <input type="radio" name="answer" value="{{$count}}" required {{($options->count() > 2 && $options[2]->status == 1)? 'checked':''}}>
                                            <i class="rounded-x"></i>
                                        </label>                                    </div>
                                    <div class="col-md-11">
                                        <input type="text" name="option3" placeholder="Option C" value="{{($options->count() > 2)? $options[2]->name:''}}">
                                    </div>
                                </div>
                            </label>
                            <label class="input">
                                <div class="row">
                                    {{--*/$count++;/*--}}
                                    <div class="col-md-1">
                                        <label class="radio">
                                            <input type="radio" name="answer" value="{{$count}}" required {{($options->count() > 3 && $options[3]->status == 1)? 'checked':''}}>
                                            <i class="rounded-x"></i>
                                        </label>                                    </div>
                                    <div class="col-md-11">
                                        <input type="text" name="option4" placeholder="Option D" value="{{($options->count() > 3)? $options[3]->name:''}}">
                                    </div>
                                </div>
                            </label>
                            <label class="input">
                                <div class="row">
                                    {{--*/$count++;/*--}}
                                    <div class="col-md-1">
                                        <label class="radio">
                                            <input type="radio" name="answer" value="{{$count}}" required {{($options->count() > 4 && $options[4]->status == 1)? 'checked':''}}>
                                            <i class="rounded-x"></i>
                                        </label>                                    </div>
                                    <div class="col-md-11">
                                        <input type="text" name="option5" placeholder="Option E" value="{{($options->count() > 4)? $options[4]->name:''}}">
                                    </div>
                                </div>
                            </label>
                        </section>
                    </div>
                </div>
            </fieldset>
            <footer>
                <div class="pull-right">
                    <button type="submit" class="btn-u">Update Question</button>
                </div>
            </footer>
        {!! Form::close() !!}
            <div class="modal fade row" id="add_info" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form action="javascript:void(0)" enctype="multipart/form-data" class="sky-form">
                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel4">Enter Additional Information</h4>
                        </div>
                        <div class="modal-body">
                            <div align="center" class="img_button">
                                <label for="file-upload" class="btn-u btn-brd btn-brd-hover rounded btn-u-sea btn-u-lg">
                                    Upload a Picture
                                </label>
                            </div>
                            <br>
                            <div align="center" class="text_button">
                                <button type="button" class="btn-u btn-brd btn-brd-hover rounded btn-u-blue btn-u-lg" onclick="$('.img_button,.text_button').hide();$('.text_area,#back_btn').show();">Enter Text</button> 
                            </div>
                            <div class="for_upload" style="display:none;">
                                <input name="image" id="file-upload" type="file" onChange="$('.text_button').hide();$('.for_upload,#back_btn').show();loadImageFileAsURL();" style="display:none;"/>
                                <br>
                                <label class="input">
                                    <input type="text" id="textAreaFileContents" name="image_description" placeholder="Image Title">
                                </label>
                                <img id="img_preview" src="" height="200" width="565" alt="Image preview...">
                            </div>
                            <div class="text_area" style="display:none;">
                                <label class="input">
                                    <input type="text" name="text_description" placeholder="Text Title">
                                </label>
                                <section>
                                    <label class="textarea">
                                        <i class="icon-prepend fa fa-file-word-o"></i>
                                        <i class="icon-append fa fa-asterisk"></i>
                                        <textarea rows="3" name="question_description" placeholder="Placeholder text"></textarea>
                                    </label>
                                </section>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <div>
                                <button type="button" class="btn-u btn-u-default" data-dismiss="modal" onclick="$('.img_button,.text_button').show();$('.text_area,.for_upload,#back_btn').hide();$('#file-upload,input[name=image_description],input[name=text_description],textarea[name=question_description]').val('')">Cancel</button>
                                <button type="button" class="btn-u btn-u-orange" style="display:none;" id="back_btn" onclick="$('.img_button,.text_button').show();$('.text_area,.for_upload,#back_btn').hide();$('#file-upload,input[name=image_description],input[name=text_description],textarea[name=question_description]').val('')">Back</button>
                                <input type="submit" class="btn-u btn-u-sea text_area add-info-save" value="Add" style="display:none;">
                                <input type="submit" class="btn-u btn-u-sea for_upload add-info-save" value="Upload" style="display:none;"> 
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
       </form>
    </div>
</div>

resources/views/admin/categorymanager.blade.php
@extends('admin_layout')

@section('pagetitle')
    EXAMINATION RESOURCES MANAGER - <small>Categories</small>
@stop
@section('maincontent')
    <div class="row margin-bottom-10">
        <div class="col-md-3 pull-right">
            <a href="{{url('admin/wbt-manager')}}" class="btn-u btn-brd btn-brd-hover rounded-2x btn-u-aqua btn-u-xs"> Back to WBT Manager</a>
        </div>
    </div>
<div class="tab-v1">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#home" data-toggle="tab">Examination Categories</a></li>
        <li><a href="#add-category" data-toggle="tab">Add New Categories</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="home">
            <div class="row">
                <div class="col-md-12">
                    <table class="table table-striped">
                         <thead>
                             <tr>
                                 <th>#</th>
                                 <th>Category Name</th>
                                 <th class="hidden-sm"><center>#Subjects</center></th>
                                 <th class="hidden-sm">Actions</th>
                             </tr>
                         </thead>
                         <tbody>
                         {{--*/$count = 1/*--}}
                            @foreach($categories as $category)
                                <tr>
                                    <td>{{$count}}</td>
                                    <td><a href="#">{{$category->name}}</a></td>
                                    <td class="hidden-sm"><center>{{$category->subject->count()}}</center></td>
                                    <td></td>
                                </tr>
                                {{--*/$count++/*--}}
                            @endforeach
                         </tbody>
                     </table> 
                </div>
            </div>
        </div>
        <div class="tab-pane fade in" id="add-category">
            <div class="row">
                <div class="col-md-12">
                    {!! Form::open(array('url' => url('admin/add-category'),'class'=>'sky-form', 'id'=>'sky-form')) !!}
                    <fieldset>
                        <div class="row">
                            <section class="col col-6">
                                <label class="input">
                                    <span>CATEGORY CODE</span>
                                    <input type="text" name="code" placeholder="Category Code" required>
                                </label>
                            </section>
                            <section class="col col-6">
                                <label class="input">
                                    <span>CATEGORY NAME</span>
                                    <input type="text" name="name" placeholder="Category Name" required>
                                </label>
                            </section>
                        </div>
                    </fieldset>
                    <footer>
                        <div class="pull-right">
                            <button type="submit" class="btn-u">Save</button>
                        </div>
                    </footer>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@stop
@section('pagejs')

@stop

resources/views/admin/examquestionedit.blade.php
@extends('admin_layout')

@section('pagetitle')
    QUESTION EDIT
@stop
@section('maincontent')
<link rel="stylesheet" href="{{ asset('assets/js/plugins/chosen/chosen.min.css') }}">
    <div class="row" id="message_div">
    </div>
<div class="tab-v1">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#home" data-toggle="tab">Examination Question Edit</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="home">
            @include('admin.addexaminationquestionedit')
        </div>
    </div>
</div>
@stop
@section('pagecss')
<link rel="stylesheet" href="{{ asset('public/assets/plugins/sky-forms-pro/skyforms/css/sky-forms.css')}}">
<link rel="stylesheet" href="{{ asset('public/assets/plugins/sky-forms-pro/skyforms/custom/custom-sky-forms.css')}}">
<link rel="stylesheet" href="{{ asset('public/assets/plugins/dataTables/jquery.dataTables.min.css') }}">
@stop
@section('pageplugins')
<script type="text/javascript" src="{{ asset('public/assets/plugins/dataTables/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('public/assets/plugins/sky-forms-pro/skyforms/js/jquery.validate.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('public/assets/plugins/sky-forms-pro/skyforms/js/jquery.maskedinput.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('public/assets/plugins/sky-forms-pro/skyforms/js/jquery-ui.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('public/assets/plugins/sky-forms-pro/skyforms/js/jquery.form.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('public/assets/js/forms/checkout.js')}}"></script>
<script type="text/javascript" src="{{ asset('public/assets/plugins/ckeditor/ckeditor.js')}}"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
			CheckoutForm.initCheckoutForm();
                    });
    CKEDITOR.replace('question');
    addInfoSave();
    // jQuery, bind an event handler or use some other way to trigger ajax call.
    function loadImageFileAsURL()
    {
        var preview = document.querySelector('#img_preview');
        var file    = document.querySelector('input[type=file]').files[0];
        var reader  = new FileReader();

        reader.addEventListener("load", function () {
            preview.src = reader.result;
        }, false);

        if (file) {
            reader.readAsDataURL(file);
        }
    }

    $(".add-info-save").click(function() {
        $("#img_select_preview,#desc_select_preview,#select_preview_title").hide();
        $("#additional_info").append("<option value=''> No additional info </option>");
        if ($(this).val() === "Upload") {
            if ($("input[name=image_description]").val() === "" || $("input[name=image]").val() === "") {
                alert("Please select an image or fill the image description");
                return false;
            }
        }
        if ($(this).val() === "Add") {
            if ($("input[name=text_description]").val() === "" || $("textarea[name=question_description]").val() === "") {
                alert("Please fill the question name or description");
                return false;
            }
        }

        var url = '{!! url("wbt/additional-info") !!}';
        var formData = {
            "_token" : "{!! csrf_token() !!}",
            "image" : $("#img_preview").prop("src"),
            "image_description" : $("input[name=image_description]").val(),
            "text_description" : $("input[name=text_description]").val(),
            "question_name" : $("textarea[name=question_description]").val()
        };

        $.ajax({
            type: 'post',
            url: url,
            data: formData,
            enctype: 'multipart/form-data',
            success: function(informations) {
                $("#additional_info").empty();
                if (formData["image_description"] === "" && formData["text_description"] === "") {
                    $("#additional_info").append("<option value='0'> No additional info </option>");
                };
                $.each(informations, function(key, value) {
                    var id = value["id"];
                    var name = value["name"];
                    var typ = value["information_type_id"];
                    var desc = value["description"];
                    $("#additional_info").append("<option value='" + id + "' data-typ='" + typ + "' data-desc='" + desc + "'>" + name + "</option>");
                });
                if (formData["image_description"] !== "" || formData["text_description"] !== "") {
                    $("#additional_info").append("<option value='0'> No additional info </option>");
                };
                $('.img_button,.text_button').show();$('.text_area,.for_upload').hide();
                $("#add_info").modal("hide");
                $('#file-upload,input[name=image_description],input[name=text_description],textarea[name=question_description]').val('');
                $("#additional_info").trigger("change");
            },
            error: function() {
                console.log("ERROR");
            }
        });
    });

    function addInfoSave() {
        $("#img_select_preview,#desc_select_preview,#select_preview_title").hide();
        $("#additional_info").append("<option value=''> No additional info </option>");
        var url2 = '{!! url("wbt/additional-infos") !!}';
        $.ajax({
            type: 'get',
            url: url2,
            success: function(informations) {
                $("#additional_info").empty();
                $("#additional_info").append("<option value='0'> No additional info </option>");
                var add_info_id = '{!! $question->question_additional_information_id !!}';
                $.each(informations, function(key, value) {
                    var id = value["id"];
                    var name = value["name"];
                    var typ = value["information_type_id"];
                    var desc = value["description"];
                    $("#additional_info").append("<option value='" + id + "' data-typ='" + typ + "' data-desc='" + desc + "'>" + name + "</option>");
                });
                if (add_info_id != 0) {
                    $('select[name="add_info"]').val(add_info_id);
                }else{
                    $('select[name="add_info"]').val(0);
                };
                $("#additional_info").trigger("change");
            },
            error: function() {
                console.log("ERROR");
            }
        });
    }
    $("#additional_info").change(function() {
        $("#img_select_preview,#desc_select_preview,#select_preview_title").hide().empty();
        if ($("option:selected", this).attr("data-typ") == 1) {
            var img_id = $('option:selected', this).val();
            var img_ext = $('option:selected', this).attr('data-desc');
            var img_url = '{!! asset("storage/additional_info/' + img_id + '.' + img_ext + '")!!}';
            $("#img_select_preview").prop("src",img_url);
            $("#select_preview_title,#img_select_preview").show();
            $("#select_preview_title").html("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;PREVIEW");
        };
        if ($("option:selected", this).attr("data-typ") == 2) {
            $("#select_preview_title,#desc_select_preview").show();
            $("#select_preview_title").html("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DESCRIPTION");
            $("#desc_select_preview").append($("option:selected", this).attr("data-desc"));
        };
    });
</script>
@stop